export const BASE_URL = "http://127.0.0.1:3000/";

//Actions
export const FETCH_RESTAURANTS_START = "FETCH_RESTAURANTS_START";
export const FETCH_RESTAURANTS_SUCCESS = "FETCH_RESTAURANTS_SUCCESS";
export const FETCH_RESTAURANTS_FAILED = "FETCH_RESTAURANTS_FAILED";
export const FILTER_RESTAURANTS = "FILTER_RESTAURANTS";

export const DELIVERY_30 = "DELIVERY_30";
export const DELIVERY_30_60 = "DELIVERY_30_60";
export const DELIVERY_ABOVE_60 = "DELIVERY_ABOVE_60";
